# -*- coding: utf-8 -*-
"""Copy of shark-tank-entrepreneur-notebook-jupyter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DWpU1ZQRqD98oJvXYyMC4LBKonbx9MoC

# Entrepreneur Agent

This notebook creates a CrewAI agent that acts as an entrepreneur pitching a business idea to a Shark Tank judge. The agent will communicate with a Judge agent running in a separate notebook through a single ngrok tunnel.

## Setup Instructions

### Prerequisites
1. **API Access**: You need either:
   - **OpenAI API Key**: Get one from [platform.openai.com](https://platform.openai.com) OR
   - **Azure OpenAI Service**: Get access from [Azure Portal](https://portal.azure.com)
2. **Judge Agent URL**: You need to run the Judge notebook first and get its public URL

### Running Order
1. Make sure you've already run the Judge notebook and have its public URL
2. Set up this Entrepreneur notebook with the Judge's URL
3. Start the pitch from this notebook
4. Respond to the judge's feedback

Let's get started!

## Step 1: Install Required Packages
"""

# Install necessary packages
# This may take a minute to complete
# pip install crewai requests openai langchain langchain_openai urllib3 crewai[azure-ai-inference]

"""## Step 2: Import Libraries"""

import os
import requests
import json
import time
from crewai import Agent, Task, Crew, Process, LLM
import threading
import openai
from langchain_openai import AzureChatOpenAI, ChatOpenAI
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
from dotenv import load_dotenv
import os

"""## Step 3: Configure API Keys

Select which API you want to use and configure the appropriate settings below.
"""
load_dotenv()


# Choose which API to use: 'openai' or 'azure'
API_TYPE = 'azure'  # Change to 'openai' to use OpenAI

# OpenAI configuration (used if API_TYPE = 'openai')
# OPENAI_API_KEY = "YOUR_OPENAI_API_KEY"  # Replace with your actual OpenAI API key
OPENAI_MODEL = "gpt-4"  # or "gpt-3.5-turbo", etc.

# Azure OpenAI configuration (used if API_TYPE = 'azure')
AZURE_API_KEY = os.getenv("AZURE_API_KEY") # "your_azure_api_key"  # Replace with your actual Azure API key
AZURE_ENDPOINT = os.getenv("AZURE_ENDPOINT")
AZURE_DEPLOYMENT = "gpt-4o-mini" # "your-deployment-name"  # Replace with your model deployment name
AZURE_API_VERSION = "2024-12-01-preview"  # Update if using a different API version

# Configure based on API type
if API_TYPE.lower() == 'openai':
    # Set up for OpenAI
    # os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY
    # Define model string for CrewAI LLM
    model_string = OPENAI_MODEL
    print(f"Using OPENAI API with model: {OPENAI_MODEL}")
elif API_TYPE.lower() == 'azure':
    # Set up for Azure OpenAI
    os.environ['AZURE_API_KEY'] = AZURE_API_KEY
    os.environ["AZURE_API_BASE"] = AZURE_ENDPOINT
    os.environ["AZURE_API_VERSION"] = AZURE_API_VERSION
    # Define model string for CrewAI LLM (with azure/ prefix)
    model_string = f"azure/{AZURE_DEPLOYMENT}"
    print(f"Using AZURE OPENAI API with deployment: {AZURE_DEPLOYMENT}")
else:
    raise ValueError("API_TYPE must be either 'openai' or 'azure'")

"""## Step 4: Test API Connection"""

# Create a simple test LLM
test_llm = LLM(model=model_string)

# Create a simple agent
test_agent = Agent(
    role="Tester",
    goal="Test API connection",
    backstory="You are a simple agent created to test the API connection.",
    verbose=True,
    llm=test_llm
)

# Create a simple task
test_task = Task(
    description="Say 'Hello, the connection is working!' Please confirm which API you're using (OpenAI or Azure).",
    expected_output="A confirmation message",
    agent=test_agent
)

# Create a crew with just this agent and task
test_crew = Crew(
    agents=[test_agent],
    tasks=[test_task],
    verbose=1  # Set to verbose to see detailed logs
)

# Run the test
try:
    print("Testing API connection with a simple task...")
    result = test_crew.kickoff()
    print("✅ Connection test successful!")
    print(f"Response: {result}")
    print(f"\n{API_TYPE.upper()} API is properly configured and working!")
except Exception as e:
    print(f"❌ Connection test failed: {str(e)}")
    print("Please check your API keys and configuration.")
    print("Detailed error:", e)

"""## Step 5: Set Up Global Variables"""

# Variable to store the server URL (from the Judge notebook)
SERVER_URL = None

# Initialize a local conversation history
conversation_history = []

"""## Step 6: Define Your Business Idea

Customize this dictionary to create your own business idea for the pitch.
"""

# Define the business idea (feel free to modify this with your own business idea)
business_idea = {
    "name": "SleepWave",
    "description": "A wearable headband that uses gentle sound frequencies and micro-vibrations to help people fall asleep faster and improve sleep quality, powered by adaptive AI that learns each user's sleep patterns.",
    "target_market": "People with sleep issues, busy professionals, students, and wellness-focused consumers",
    "revenue_model": "Device sales + optional monthly subscription for personalized sleep analytics and advanced sleep-training programs",
    "current_traction": "2,000 early sign-ups, successful pilot with 120 users showing 32% faster sleep onset",
    "investment_needed": "$400,000 for 12% equity",
    "use_of_funds": "Manufacturing scale-up, mobile app development, clinical validation, and marketing"
}

# Example alternative business ideas you can use (uncomment and modify as needed):

# Tech SaaS Business
# business_idea = {
#     "name": "DataSense AI",
#     "description": "An AI-powered data analysis platform for small and medium businesses",
#     "target_market": "SMBs without dedicated data science teams",
#     "revenue_model": "Tiered SaaS subscription based on data volume and features",
#     "current_traction": "50 paying customers, $15,000 MRR, 15% month-over-month growth",
#     "investment_needed": "$500,000 for 15% equity",
#     "use_of_funds": "Expanding engineering team, enhancing AI capabilities, sales and marketing"
# }

# Consumer Product Business
# business_idea = {
#     "name": "GreenPlate",
#     "description": "Biodegradable, plant-based food containers that replace single-use plastics",
#     "target_market": "Eco-conscious restaurants, food delivery services, and consumers",
#     "revenue_model": "Direct B2B sales to restaurants and wholesale to retailers",
#     "current_traction": "Partnerships with 10 local restaurants, LOIs from 2 regional chains",
#     "investment_needed": "$250,000 for 20% equity",
#     "use_of_funds": "Scaling production, certifications, and expanding distribution channels"
# }

"""## Step 7: Create the Entrepreneur Agent

Feel free to customize the entrepreneur's personality by modifying the backstory.
"""

# Create the Entrepreneur Agent
entrepreneur_agent = Agent(
    role="Tech Startup Entrepreneur",
    goal="Pitch your innovative business idea and secure investment",
    backstory="""You are a scrappy and determined founder who built your startup out of frustration with a real
    problem you personally experienced for years. You didn’t come from money—your early prototypes were built
    in your living room with borrowed equipment and late-night YouTube tutorials. After facing multiple failures,
    you finally created a product that people genuinely love.

    You’re humble but sharp, and you know your numbers because you had to learn them the hard way. You speak with
    honesty and passion, and your strength is your deep understanding of your users and the problem you're solving.
    You’re here because you believe the right investor can help you scale—not just with money, but with guidance,
    networks, and real-world experience.""",
    verbose=True,
    allow_delegation=False,
    llm=LLM(model=model_string)
)

"""## Step 8: Define Helper Functions"""

# Function to set the server URL
def set_server_url(url):
    """Set the server URL after getting it from the Judge notebook"""
    global SERVER_URL
    # Convert HTTPS to HTTP to avoid SSL verification issues
    SERVER_URL = url.replace("https://", "http://")
    print(f"Server URL set to: {SERVER_URL}")
    return SERVER_URL

# Function to check conversation history
def check_conversation():
    """Display the current conversation history"""
    print("\n=== CONVERSATION HISTORY ===\n")
    for message in conversation_history:
        print(f"-{message['role']}:\n {message['content']}...\n")
        print("-" * 50)

    return conversation_history

# Function to save conversation history to JSON file
def save_conversation_to_json(filename=None):
    """Save the conversation history to a JSON file"""
    global conversation_history
    
    # Debug: Show current state
    print(f"📊 Current conversation history length: {len(conversation_history)} messages")
    if len(conversation_history) == 0:
        print("⚠️  Warning: Conversation history is empty. Make sure you've run initiate_pitch() or send_message() first.")
    
    if filename is None:
        # Generate filename with timestamp
        timestamp = time.strftime("%Y%m%d_%H%M%S")
        filename = f"entrepreneur_conversation_{timestamp}.json"
    
    # Prepare data to save
    data_to_save = {
        "business_idea": business_idea,
        "conversation_history": conversation_history,
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        "total_messages": len(conversation_history)
    }
    
    try:
        # Get the full absolute path
        full_path = os.path.abspath(filename)
        with open(filename, 'w', encoding='utf-8') as f:
            json.dump(data_to_save, f, indent=2, ensure_ascii=False)
        print(f"✅ Conversation saved to: {full_path}")
        print(f"   - Business idea: ✓")
        print(f"   - Conversation messages: {len(conversation_history)}")
        return full_path
    except Exception as e:
        print(f"❌ Error saving conversation: {e}")
        return None

# Function to send a message to the server and get response
def send_message(content, sender="Entrepreneur", auto_save=False):
    """Send a message to the server and get the response
    
    Args:
        content: Message content to send
        sender: Sender name (default: "Entrepreneur")
        auto_save: If True, automatically save conversation to JSON after receiving response
    """
    global conversation_history

    if not SERVER_URL:
        print("ERROR: Server URL not set. Please run set_server_url() first.")
        return None

    # Add message to local conversation history
    conversation_history.append({"role": sender, "content": content})

    # Prepare the request
    try:
        response = requests.post(
            f"{SERVER_URL}/submit_message",
            json={"content": content, "sender": sender},
            verify=False  # Disable SSL verification for ngrok
        )

        if response.status_code != 200:
            print(f"Error sending message: {response.text}")
            return None

        response_data = response.json()

        # Handle multiple responses (new format) or single response (old format)
        if "messages" in response_data:
            # New format: multiple messages from different judges
            for msg in response_data["messages"]:
                conversation_history.append({
                    "role": msg["sender"],
                    "content": msg["response"]
                })
                print(f"Received response from {msg['sender']}: {msg['response'][:100]}...")
        elif "response" in response_data and "sender" in response_data:
            # Old format: single response
            conversation_history.append({
                "role": response_data["sender"],
                "content": response_data["response"]
            })
            print(f"Received response from {response_data['sender']}: {response_data['response'][:100]}...")

        # Auto-save if requested
        if auto_save:
            save_conversation_to_json()

        return response_data
    except requests.RequestException as e:
        print(f"Error communicating with server: {e}")
        return None

"""## Step 9: Set the Server URL

**IMPORTANT**: You need to have the Judge's public URL from the other notebook. Replace the placeholder below with that URL.
"""

# Replace the placeholder with the URL you copied from the Judge notebook
set_server_url('https://stringless-questingly-keagan.ngrok-free.dev')


"""## Step 10: Create and Send Initial Pitch"""

def initiate_pitch():
    """Start the pitch process"""
    if not SERVER_URL:
        print("ERROR: Server URL not set. Please run set_server_url() first.")
        return None

    print("Creating initial pitch...")

    # Create the initial pitch
    task = Task(
        description=f"""Create a compelling initial pitch for your business idea.

        Your business idea:
        Name: {business_idea['name']}
        Description: {business_idea['description']}
        Target Market: {business_idea['target_market']}
        Revenue Model: {business_idea['revenue_model']}
        Current Traction: {business_idea['current_traction']}
        Investment Needed: {business_idea['investment_needed']}
        Use of Funds: {business_idea['use_of_funds']}

        Be enthusiastic and concise. Highlight the problem you're solving, your solution,
        market opportunity, and why your team is uniquely positioned to succeed.
        End with a clear ask for the investment amount and equity offer.""",
        expected_output="A compelling business pitch for Shark Tank",
        agent=entrepreneur_agent,
    )

    # Create a crew with just the entrepreneur agent
    crew = Crew(
        agents=[entrepreneur_agent],
        tasks=[task],
    )

    # Execute the task
    result = crew.kickoff()
    pitch_content = result.raw

    print("Initial pitch created. Sending to the judge...")

    # Send the pitch to the server
    send_message(pitch_content)

    return pitch_content

# Start the pitch
# initiate_pitch()

"""## Step 11: Check Conversation History

Run this cell to see the current conversation history.
"""

# Check the conversation history
# check_conversation()

"""## Step 12: Respond to Judge's Feedback

Run this cell to respond to the judge's feedback.
"""

def respond_to_feedback():
    """Generate and send a response to the judge's feedback"""
    if not SERVER_URL:
        print("ERROR: Server URL not set. Please run set_server_url() first.")
        return None

    if len(conversation_history) < 2:
        print("ERROR: No feedback from judge to respond to yet.")
        return None

    # Get the last message from the judge
    judge_feedback = None
    for message in reversed(conversation_history):
        if message["role"] == "Judge":
            judge_feedback = message["content"]
            break

    if not judge_feedback:
        print("ERROR: No feedback from judge found in conversation history.")
        return None

    print("Creating response to judge's feedback...")

    # Create the context from conversation history
    context = "\n".join([f"{msg['role']}: {msg['content']}" for msg in conversation_history])

    # Create a task to respond to the feedback
    task = Task(
        description=f"""Respond to the Shark Tank judge's feedback or questions.

        Your business idea:
        Name: {business_idea['name']}
        Description: {business_idea['description']}
        Target Market: {business_idea['target_market']}
        Revenue Model: {business_idea['revenue_model']}
        Current Traction: {business_idea['current_traction']}
        Investment Needed: {business_idea['investment_needed']}
        Use of Funds: {business_idea['use_of_funds']}

        Conversation history:
        {context}

        Respond to the judge's feedback or questions thoughtfully.
        Address any concerns they raise, provide additional details about your business when needed,
        and try to convince them of the value of your idea. Be confident but not arrogant.""",
        expected_output="A thoughtful response to the judge's feedback",
        agent=entrepreneur_agent,
    )

    # Create a crew with just the entrepreneur agent
    crew = Crew(
        agents=[entrepreneur_agent],
        tasks=[task],
    )

    # Execute the task
    result = crew.kickoff()
    response_content = result.raw

    print("Response created. Sending to the judge...")

    # Send the response to the server
    send_message(response_content)

    return response_content

# Respond to the judge's feedback
# respond_to_feedback()

"""## Keep Notebook Active

Run this cell periodically to keep the notebook connection active.
"""

# Run this cell periodically to keep the notebook active
def keep_alive():
    """Keep the notebook connection active"""
    print("Keeping connection alive...")
    print(f"Current time: {time.strftime('%H:%M:%S')}")
    print(f"Current conversation length: {len(conversation_history)} messages")

# keep_alive()

"""## Save Conversation to JSON

Run this cell to save the conversation history to a JSON file.
You can also call save_conversation_to_json() with a custom filename.

IMPORTANT: Make sure you've run initiate_pitch() and received responses from the judge
before saving, otherwise the conversation_history will be empty.
"""

# Save conversation to JSON file
# Uncomment the line below AFTER you've had a conversation with the judge
save_conversation_to_json("conversation.json")  # Uses auto-generated filename with timestamp
# save_conversation_to_json("my_conversation.json")  # Or specify a custom filename

if __name__ == "__main__":
    # Set the server URL (update this with the Judge's URL)
    if not SERVER_URL:
        print("Please set the SERVER_URL first!")
        print("You can do this by calling: set_server_url('https://your-judge-url.ngrok-free.dev')")
        exit(1)
    
    # Start the pitch
    initiate_pitch()
    
    # Wait a bit for response
    time.sleep(3)
    
    # Check conversation
    check_conversation()
    
    # Save conversation to JSON after receiving responses
    if len(conversation_history) > 0:
        print("\n💾 Saving conversation to JSON...")
        save_conversation_to_json("conversation.json")
    else:
        print("\n⚠️  No conversation history to save yet. Make sure the judge has responded.")
    
    # Optionally respond to feedback
    # Uncomment the line below to automatically respond
    # respond_to_feedback()